### ISSUE TITLE
The product reducer and action: keeps loading  the URL {product/api/product/:id} resulting in the product screen failing any idea what's causing this ???

### ISSUE THREAD

**Issue by Masemola-NK** [bradtraversy/proshop_mern#165] opened 2021-07-10 11:17 UTC
The product reducer and action: keeps loading  the URL {product/api/product/:id} resulting in the product screen failing any idea what's causing this ???

_Originally posted by @Masemola-NK in https://github.com/bradtraversy/proshop_mern/issues/88#issuecomment-877620550_

**Comment by talhabintariq** [comment] 2021-07-19 00:37
@Masemola-NK I haven't seen the final code but it sounds like the action is being called again and again. That can be fixed by updating the dependencies in the `useEffect`.

**Comment by basir** [comment] 2021-07-19 04:18
hello there,
ask it in Udemy Q/A and mention screenshot of error and source code. the issue is in useEffect. please compare your code with this file:
https://github.com/bradtraversy/proshop_mern/blob/master/frontend/src/screens/ProductScreen.js

**Closed by basir** 2021-07-19 04:18 UTC
