### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by fangqiank** [bradtraversy/proshop_mern#7] opened 2020-10-01 18:36 UTC
<img width="972" alt="screenshot" src="https://user-images.githubusercontent.com/1538782/94849425-a1625380-03e2-11eb-84b7-cb0dace881d6.png">
Tested the Api for order by postman and encountered "TypeError: Cannot read property '1' of null" error

**Comment by bradtraversy** [comment] 2020-10-02 13:32
Can you post your code for that particular controller function?

**Comment by fangqiank** [comment] 2020-10-02 21:02
I just

> Can you post your code for that particular controller function?

Hi Brad,

I just copy your code and test api in postman

**Comment by bradtraversy** [comment] 2020-10-03 14:05
This works fine. Please make sure you login with an admin token. Closing since I can not reproduce. The controller function is only two lines and it is just fetching orders. I don't see how you could be getting this.

![Screen Shot 2020-10-03 at 10 04 26 AM](https://user-images.githubusercontent.com/5550850/94993578-fd061b80-055f-11eb-8104-385d3e1c55b7.png)

**Closed by bradtraversy** 2020-10-03 14:05 UTC
